version: "3"

networks:
  stack_dev:
    external: true

services:
  intellect_back:
    image: golang:1.19.4
    container_name: "intellect_back"
    networks:
      - stack_dev
    ports:
      - "5080:8000"
    volumes:
      - ${DEVPATHCLIENTES}/intellect/back:/app
      - ${DEVPATHCLIENTES}/intellect/server/cespare:/go/pkg/mod/github.com/cespare
      - ${DEVPATHCLIENTES}/intellect/server/reflex:/go/bin/reflex
    command: "/bin/sh -c 'cd /app && reflex -c /app/reflex.conf'"

  intellect_front:
    container_name: "intellect_front"
    image: "node:lts-alpine"
    working_dir: /app
    networks:
      - stack_dev
    volumes:
      - ${DEVPATHCLIENTES}/intellect/front:/app
    command: "npm run dev"
    deploy:
      resources:
        limits:
          memory: 1000M
    ports:
      - "8081:3000"
