version: "3"

networks:
  stack_ponte:
    external: true

services:
  frontend_intellect:
    container_name: "frontend_intellect"
    image: "webdevops/apache:latest"
    networks:
      - stack_ponte
    volumes:
      - "${PATHPESSOAL}/intellect/front-intellect/dist:/app"
    ports:
      - 4080:80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.intellect.rule=Host(`intellect.${DOMAIN}`,`www.intellect.${DOMAIN}`)"
      - "traefik.http.services.intellect.loadbalancer.server.port=80"

  backend_intellect:
    container_name: "backend_intellect"
    image: golang:1.16.3
    networks:
      - stack_ponte
    volumes:
      - ${PATHPESSOAL}/intellect/backgo:/app
    ports:
      - 4020:8000
    command: "/bin/sh -c 'cd /app && ls && ./main'"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.apiintellect.rule=Host(`apiintellect.${DOMAIN}`)"
      - "traefik.http.services.apiintellect.loadbalancer.server.port=4020"
